### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by Thundros** [moni-js/Moxxi#2]
Hi, I went to download this & noticed that game.js has 0 bytes of data. Can you please fix this? Thank you! :)

**Comment by NotMoni** [comment]
Hey, Sure. This is one of the less worked on projects. Would you want to join this organization, if so join this Discord Guild https://discord.gg/jQdFFH6 You could work with us together? For your question: sure Ill pick up work on this project soon.

**Comment by Thundros** [comment]
It's still missing the files. No game.js, no index.html.... :(

**Comment by Thundros** [comment]
hello?

**Comment by NotMoni** [comment]
Yes, I am working On the game. If you want to see work done, you can also work on it.

**Comment by ghost** [comment]
This project isn't ready yet!
